{{- if index .Values "keycloak-operator" "enabled" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.15.1
    app.quarkus.io/vcs-uri: https://github.com/keycloak/keycloak.git
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: quarkus
  name: keycloak-operator
  namespace: {{ include "keycloak-custom.namespace" . }}
{{- end }}
